package jtmp

import (
	"os"
)

// Root template directory (autogenerated templates)
const AutoTemplateDir = "templates-auto"

// Template names
const ZFSinit = "zfs-init.sh.template"
const ZFSstatus = "zfs-status.sh.template"
const ZFSdestroy = "zfs-destroy.sh.template"

const ImgInit = "img-init.sh.template"
const ImgRemove = "img-remove.sh.template"

const BridgeRC = "bridge-rc.conf.template"

// Create and clear templates dir
func CreateTemplateDir() (e error) {
	if e = os.RemoveAll(AutoTemplateDir); e != nil {
		return e
	}
	if e = os.MkdirAll(AutoTemplateDir, 0o755); e != nil {
		return e
	}

	return nil
}
